var ejsExcel = require("ejsexcel");
var fs = require("fs");
//获得Excel模板的buffer对象
var exlBuf = fs.readFileSync("./report.xlsx");

//数据源
var data =[ 
    [{table_name:"标的列表"},{table_name:"回款订单列表"}],
    [          
        {
            "id": "BD20170515-8051",
            "type": 1,
            "name": "美国房地产抵押系列C",
            "rate": 5,
            "status": 3,
            "actual_raise_amount": 225000,
            "interest_end_date": "2018-10-31T00:05:51.000Z",
            "amount": 10000,
            "repay_amount": 10470,
            "orig_id": "E0862018010800-1361",
            "is_repeat": 0,
            "uid": "60ECA5A8-87C5-413B-B1AF-9BAEC6DB1472",
            "pre_status": null,
            "flow_id": 2803,
            "mobilePrefix": "86",
            "mobile": "+86 18500239468",
            "accountType": "intl",
            "userType": "gbl",
            "IntlUserName": "liwei",
            "usaUserName": "liwei",
            "principal_settle": 10000,
            "interest": 500,
            "interest_coupon": 3000,
            "action_description": "滞留"
        },
        {
            "id": "BD20170515-8051",
            "type": 1,
            "name": "美国房地产抵押系列C",
            "rate": 5,
            "status": 3,
            "actual_raise_amount": 225000,
            "interest_end_date": "2018-10-31T00:05:51.000Z",
            "amount": 50000,
            "repay_amount": 53587.83,
            "orig_id": "E0862017112800-2646",
            "is_repeat": 0,
            "uid": "120A2358-A537-435A-9915-A10258DFF134",
            "pre_status": null,
            "flow_id": 2679,
            "mobilePrefix": "1",
            "mobile": "+1 17600525555",
            "accountType": "intl",
            "userType": "gbl",
            "IntlUserName": "GD",
            "usaUserName": null,
            "principal_settle": 50000,
            "interest": 3587.83,
            "interest_coupon": 0,
            "prew_flow_info": {
                "newPrincipal": 100000,
                "backPrincipal": 0,
                "backInterest": 0
            },
            "cur_order_flow_cop": {
                "selfPrincipal": 50000,
                "selfInterest": 3587.83,
                "selfInterestCoupon": 0
            },
            "ACTION_STORE": [
                {
                    "uid": "120A2358-A537-435A-9915-A10258DFF134",
                    "id": 2687,
                    "order_no": "1170",
                    "business_type": 2,
                    "change_type": 3,
                    "date": "2018-01-02T07:38:19.000Z",
                    "frozen_amount": 217691.83,
                    "amount": 0,
                    "order_id": null,
                    "principal": null,
                    "principal_settle": null,
                    "interest": null,
                    "interest_coupon": null,
                    "pre_order_id": null,
                    "pre_principal": null,
                    "pre_principal_settle": null,
                    "pre_interest": null,
                    "pre_interest_coupon": null,
                    "action_back_interest_amount": 3587.83,
                    "action_back_principal_amount": 50000,
                    "action_new_principal_amount": 164104,
                    "action_description": "资金转出(全额)"
                }
            ],
            "SUN_DETAILS_INFO": {
                "sum_details_used_amount": 53587.83,
                "sum_details_invest_principal_amount": 0,
                "sum_details_invest_interest_amount": 0,
                "sum_details_draw_principal_amount": 50000,
                "sum_details_draw_interest_amount": 3587.83
            },
            "ACTION_STORE_DETAIL": {
                "uid": "120A2358-A537-435A-9915-A10258DFF134",
                "id": 2687,
                "order_no": "1170",
                "business_type": 2,
                "change_type": 3,
                "date": "2018-01-02T07:38:19.000Z",
                "frozen_amount": 217691.83,
                "amount": 0,
                "order_id": null,
                "principal": null,
                "principal_settle": null,
                "interest": null,
                "interest_coupon": null,
                "pre_order_id": null,
                "pre_principal": null,
                "pre_principal_settle": null,
                "pre_interest": null,
                "pre_interest_coupon": null,
                "action_back_interest_amount": 3587.83,
                "action_back_principal_amount": 50000,
                "action_new_principal_amount": 164104,
                "action_description": "资金转出(全额)"
            },
            "ACTION_STORE_LENGTH": 1
        },
        {
            "id": "BD20170515-8051",
            "type": 1,
            "name": "美国房地产抵押系列C",
            "rate": 5,
            "status": 3,
            "actual_raise_amount": 225000,
            "interest_end_date": "2018-10-31T00:05:51.000Z",
            "amount": 60000,
            "repay_amount": 64104,
            "orig_id": "E0862018010200-6421",
            "is_repeat": 0,
            "uid": "120A2358-A537-435A-9915-A10258DFF134",
            "pre_status": null,
            "flow_id": 2686,
            "mobilePrefix": "1",
            "mobile": "+1 17600525555",
            "accountType": "intl",
            "userType": "gbl",
            "IntlUserName": "GD",
            "usaUserName": null,
            "principal_settle": 60000,
            "interest": 4104,
            "interest_coupon": 0,
            "prew_flow_info": {
                "newPrincipal": 100000,
                "backPrincipal": 50000,
                "backInterest": 3587.83
            },
            "cur_order_flow_cop": {
                "selfPrincipal": 60000,
                "selfInterest": 4104,
                "selfInterestCoupon": 0
            },
            "ACTION_STORE": [
                {
                    "uid": "120A2358-A537-435A-9915-A10258DFF134",
                    "id": 2687,
                    "order_no": "1170",
                    "business_type": 2,
                    "change_type": 3,
                    "date": "2018-01-02T07:38:19.000Z",
                    "frozen_amount": 217691.83,
                    "amount": 0,
                    "order_id": null,
                    "principal": null,
                    "principal_settle": null,
                    "interest": null,
                    "interest_coupon": null,
                    "pre_order_id": null,
                    "pre_principal": null,
                    "pre_principal_settle": null,
                    "pre_interest": null,
                    "pre_interest_coupon": null,
                    "action_back_interest_amount": 4104,
                    "action_back_principal_amount": 60000,
                    "action_new_principal_amount": 153587.83,
                    "action_description": "资金转出(利息+回款本金+新增本金)"
                }
            ],
            "SUN_DETAILS_INFO": {
                "sum_details_used_amount": 64104,
                "sum_details_invest_principal_amount": 0,
                "sum_details_invest_interest_amount": 0,
                "sum_details_draw_principal_amount": 60000,
                "sum_details_draw_interest_amount": 4104
            },
            "ACTION_STORE_DETAIL": {
                "uid": "120A2358-A537-435A-9915-A10258DFF134",
                "id": 2687,
                "order_no": "1170",
                "business_type": 2,
                "change_type": 3,
                "date": "2018-01-02T07:38:19.000Z",
                "frozen_amount": 217691.83,
                "amount": 0,
                "order_id": null,
                "principal": null,
                "principal_settle": null,
                "interest": null,
                "interest_coupon": null,
                "pre_order_id": null,
                "pre_principal": null,
                "pre_principal_settle": null,
                "pre_interest": null,
                "pre_interest_coupon": null,
                "action_back_interest_amount": 4104,
                "action_back_principal_amount": 60000,
                "action_new_principal_amount": 153587.83,
                "action_description": "资金转出(利息+回款本金+新增本金)"
            },
            "ACTION_STORE_LENGTH": 1
        },
        {
            "id": "BD20170515-8051",
            "type": 1,
            "name": "美国房地产抵押系列C",
            "rate": 5,
            "status": 3,
            "actual_raise_amount": 225000,
            "interest_end_date": "2018-10-31T00:05:51.000Z",
            "amount": 2000,
            "repay_amount": 2120,
            "orig_id": "E0862018020500-10310",
            "is_repeat": 1,
            "uid": "3967E279-02A8-4777-B68F-4BDCDE34A292",
            "pre_status": 5,
            "flow_id": 3197,
            "mobilePrefix": "1",
            "mobile": "+1 17700123456",
            "accountType": "intl",
            "userType": "gbl",
            "IntlUserName": "xzxz",
            "usaUserName": null,
            "principal_settle": 2000,
            "interest": 120,
            "interest_coupon": 0,
            "prew_flow_info": {
                "newPrincipal": 0,
                "backPrincipal": 0,
                "backInterest": 0
            },
            "cur_order_flow_cop": {
                "selfPrincipal": 2000,
                "selfInterest": 120,
                "selfInterestCoupon": 0
            },
            "ACTION_STORE": [
                {
                    "uid": "3967E279-02A8-4777-B68F-4BDCDE34A292",
                    "id": 3203,
                    "order_no": "E0862018020517-40715",
                    "business_type": 3,
                    "change_type": 6,
                    "date": "2018-02-05T12:22:57.000Z",
                    "frozen_amount": 3180,
                    "amount": 3180,
                    "order_id": null,
                    "principal": null,
                    "principal_settle": null,
                    "interest": null,
                    "interest_coupon": null,
                    "pre_order_id": null,
                    "pre_principal": null,
                    "pre_principal_settle": null,
                    "pre_interest": null,
                    "pre_interest_coupon": null,
                    "action_description": "投资（本金+利息）",
                    "action_back_principal_amount": 2000,
                    "action_back_interest_amount": 120
                }
            ],
            "SUN_DETAILS_INFO": {
                "sum_details_used_amount": 2120,
                "sum_details_invest_principal_amount": 2000,
                "sum_details_invest_interest_amount": 120,
                "sum_details_draw_principal_amount": 0,
                "sum_details_draw_interest_amount": 0
            },
            "ACTION_STORE_DETAIL": {
                "uid": "3967E279-02A8-4777-B68F-4BDCDE34A292",
                "id": 3203,
                "order_no": "E0862018020517-40715",
                "business_type": 3,
                "change_type": 6,
                "date": "2018-02-05T12:22:57.000Z",
                "frozen_amount": 3180,
                "amount": 3180,
                "order_id": null,
                "principal": null,
                "principal_settle": null,
                "interest": null,
                "interest_coupon": null,
                "pre_order_id": null,
                "pre_principal": null,
                "pre_principal_settle": null,
                "pre_interest": null,
                "pre_interest_coupon": null,
                "action_description": "投资（本金+利息）",
                "action_back_principal_amount": 2000,
                "action_back_interest_amount": 120
            },
            "ACTION_STORE_LENGTH": 1
        },
        {
            "id": "BD20170515-8051",
            "type": 1,
            "name": "美国房地产抵押系列C",
            "rate": 5,
            "status": 3,
            "actual_raise_amount": 225000,
            "interest_end_date": "2018-10-31T00:05:51.000Z",
            "amount": 3000,
            "repay_amount": 3180,
            "orig_id": "E0862018020500-7166",
            "is_repeat": 1,
            "uid": "3967E279-02A8-4777-B68F-4BDCDE34A292",
            "pre_status": 3,
            "flow_id": 3199,
            "mobilePrefix": "1",
            "mobile": "+1 17700123456",
            "accountType": "intl",
            "userType": "gbl",
            "IntlUserName": "xzxz",
            "usaUserName": null,
            "principal_settle": 3000,
            "interest": 180,
            "interest_coupon": 0,
            "prew_flow_info": {
                "newPrincipal": 0,
                "backPrincipal": 2000,
                "backInterest": 120
            },
            "cur_order_flow_cop": {
                "selfPrincipal": 3000,
                "selfInterest": 180,
                "selfInterestCoupon": 0
            },
            "ACTION_STORE": [
                {
                    "uid": "3967E279-02A8-4777-B68F-4BDCDE34A292",
                    "id": 3203,
                    "order_no": "E0862018020517-40715",
                    "business_type": 3,
                    "change_type": 6,
                    "date": "2018-02-05T12:22:57.000Z",
                    "frozen_amount": 3180,
                    "amount": 3180,
                    "order_id": null,
                    "principal": null,
                    "principal_settle": null,
                    "interest": null,
                    "interest_coupon": null,
                    "pre_order_id": null,
                    "pre_principal": null,
                    "pre_principal_settle": null,
                    "pre_interest": null,
                    "pre_interest_coupon": null,
                    "action_back_principal_amount": 1180,
                    "action_back_interest_amount": 0,
                    "action_new_principal_amount": 0,
                    "action_description": "投资(本金)"
                },
                {
                    "uid": "3967E279-02A8-4777-B68F-4BDCDE34A292",
                    "id": 3204,
                    "order_no": "E0862018020517-45518",
                    "business_type": 3,
                    "change_type": 6,
                    "date": "2018-02-05T12:29:26.000Z",
                    "frozen_amount": 1060,
                    "amount": 1060,
                    "order_id": null,
                    "principal": null,
                    "principal_settle": null,
                    "interest": null,
                    "interest_coupon": null,
                    "pre_order_id": null,
                    "pre_principal": null,
                    "pre_principal_settle": null,
                    "pre_interest": null,
                    "pre_interest_coupon": null,
                    "action_back_principal_amount": 1060,
                    "action_back_interest_amount": 0,
                    "action_new_principal_amount": 0,
                    "action_description": "投资(本金)"
                },
                {
                    "uid": "3967E279-02A8-4777-B68F-4BDCDE34A292",
                    "id": 3206,
                    "order_no": "E0862018020517-45518-2-2",
                    "business_type": 3,
                    "change_type": 6,
                    "date": "2018-02-05T12:29:29.000Z",
                    "frozen_amount": 2120,
                    "amount": 3180,
                    "order_id": null,
                    "principal": null,
                    "principal_settle": null,
                    "interest": null,
                    "interest_coupon": null,
                    "pre_order_id": null,
                    "pre_principal": null,
                    "pre_principal_settle": null,
                    "pre_interest": null,
                    "pre_interest_coupon": null,
                    "action_back_principal_amount": 760,
                    "action_back_interest_amount": 0,
                    "action_new_principal_amount": 0,
                    "action_description": "投资(本金)"
                }
            ],
            "SUN_DETAILS_INFO": {
                "sum_details_used_amount": 3000,
                "sum_details_invest_principal_amount": 3000,
                "sum_details_invest_interest_amount": 0,
                "sum_details_draw_principal_amount": 0,
                "sum_details_draw_interest_amount": 0
            },
            "ACTION_STORE_DETAIL": {
                "uid": "3967E279-02A8-4777-B68F-4BDCDE34A292",
                "id": 3206,
                "order_no": "E0862018020517-45518-2-2",
                "business_type": 3,
                "change_type": 6,
                "date": "2018-02-05T12:29:29.000Z",
                "frozen_amount": 2120,
                "amount": 3180,
                "order_id": null,
                "principal": null,
                "principal_settle": null,
                "interest": null,
                "interest_coupon": null,
                "pre_order_id": null,
                "pre_principal": null,
                "pre_principal_settle": null,
                "pre_interest": null,
                "pre_interest_coupon": null,
                "action_back_principal_amount": 760,
                "action_back_interest_amount": 0,
                "action_new_principal_amount": 0,
                "action_description": "投资(本金)"
            },
            "ACTION_STORE_LENGTH": 3
        }
    ]
];

//用数据源(对象)data渲染Excel模板
ejsExcel.renderExcel(exlBuf, data).then(function(exlBuf2){
	fs.writeFileSync("./report2.xlsx", exlBuf2);
	console.log("生成report2.xlsx");
}).catch(function(err) {
	console.error(err);
});

